### ISSUE TITLE
Search for a Storybook addon to demonstrate components repeatably

### ISSUE THREAD

**Issue by jlangy** [thebuttonclan/pangolin#194]
As a user,
When I visit the component-library storybook,
I want to have a well explained and consistent page for each component.

Action:
- [x] Search for an addon that will display the three HTML, HTML+CSS, HTML+CSS+JS states, and include documentation explaining the component in each state and the reason to use  in a way that will make it easy to be consistent.

See #202 for mock-up

**Comment by jlangy** [comment]
This addon could help us pivot to display all themes:
- https://storybook.js.org/addons/storybook-addon-theme-playground/

**Comment by jlangy** [comment]
Also if we want to show responsiveness there is a good one [here](https://storybook.js.org/addons/storybook-addon-responsive-views)

**Comment by jlangy** [comment]
Built in to toggle javascript:
- https://storybook.js.org/addons/storybook-addon-javascript-toggler/
Doesn't seem to be working anymore, hasn't been updated in a bit. Javascript is still running when toggled off

Built in to show the html (the actual code, not html only component). Could be useful if we want to clearly show things like name, id, for coming through the the actual html 
- https://github.com/khriztianmoreno/storybook-addon-raw-styled-component/

**Comment by jlangy** [comment]
I think some of these will be useful to consider adding in, for the core progressive enhancement toggling I don't see anything that can meet our requirements

**Comment by jlangy** [comment]
I will work on seeing what parts of what we already have/example code from the js toggler can be integrated into a custom addon (not design, just functionality)

**Comment by jaimiebutton** [comment]
Looks like there's some cool potential here. We'll have to figure out what kind of toggle is best - progressive enhancement or theme. Either way, looks very promising!

**Comment by jlangy** [comment]
I think we can do both, looks like the theme one there are a bunch of options, I think for PE we will probably have to make one, but looking into it I don't think it'll be too much work. For the display, I was thinking of putting the toggles into the top toolbar for turning off JS and CSS, what do you think design-wise for that?

**Comment by jaimiebutton** [comment]
Is it hard to change once we put it somewhere? Top toolbar sounds good to me for now, and we'll probably get some feedback on its discoverability/usability when we test it with people :)

**Comment by jlangy** [comment]
Not hard, we have three options, can either make a panel for it (the bottom space where you can toggle to accessibility), a tab for it (the top row where docs is), or the toolbar. Moving between the three won't be too much effort I dont think, but if you think a different one of those three might work better let me know

**Comment by jaimiebutton** [comment]
Yeah I'm with you! Toolbar seems like the best way to go.

**Comment by jlangy** [comment]
# Result

After exploring above options, it seems a custom addon will be the easiest implementation
