### ISSUE TITLE
update bcgov filepicker component

### ISSUE THREAD

**Issue by jlangy** [thebuttonclan/pangolin#211]
Update the filepicker story in storybook to list all of its props, and document it's use cases and value. Use the filepicker to check for any bugs that may exist

- [x] Storybook documentation
- [x] Bugs check

**Comment by jaimiebutton** [comment]
This may be dumb, so disregard if all is well here.

Is it normal to not have the hand icon as the cursor when hovering over the file picker?
<img width="665" alt="Screen Shot 2021-05-31 at 12 31 17 PM" src="https://user-images.githubusercontent.com/80294638/120234116-2456da80-c20c-11eb-80f4-cb83c7341288.png">

**Comment by jlangy** [comment]
No that's a good catch, can definitely change the cursor. Would you be okay with noting these on issue #188, I don't think we have to make an issue for each fix but it'll be easy to grab them all from one spot
