### ISSUE TITLE
update bcgov header component

### ISSUE THREAD

**Issue by jlangy** [thebuttonclan/pangolin#215]
Update the header story in storybook to list all of its props, and document it's use cases and value. Use the header to check for any bugs that may exist

- [x] Storybook documentation
- [x] Bugs check

**Comment by jaimiebutton** [comment]
A few comments on header:

1. Does the header look weird on your end too or is it just my screen? (with the logo hanging off, etc.) See attached.
<img width="1035" alt="Screen Shot 2021-05-31 at 12 16 43 PM" src="https://user-images.githubusercontent.com/80294638/120233336-6ed75780-c20a-11eb-8074-3f6baa19c603.png">

2. We're just missing the letter 'c' in the description: 
_For fully enhanced environments, headers **can** be used_...

**Comment by jlangy** [comment]
Looked alright on mine, you are on safari right?
