### ISSUE TITLE
Create "Toolkit in Action" page

### ISSUE THREAD

**Issue by eazeredo** [thebuttonclan/pangolin#290]
- [x] Mockup - [XD Mockup](https://xd.adobe.com/view/92e97b1e-d0a5-4879-b1f2-52501ad74547-c7ba/)
- [x] Content - [Notion Page](https://www.notion.so/buttoninc/Toolkit-in-Action-1614ce361f924364b7d8bea39ece38c4) 
- [x] Create in Storybook

**Comment by kriscooke** [comment]
This appears to have already been completed ([bcgov themed here](https://button-inc.github.io/service-development-toolkit/@button-inc/bcgov-theme/index.html?path=/docs/components-page--default), and [button themed](https://button-inc.github.io/service-development-toolkit/@button-inc/button-theme/index.html?path=/story/page--default)), or am I mistaken and there's something more to this task?

**Comment by eazeredo** [comment]
@kriscooke, the idea is:

1.  to add the text above the component itself
2.  move the page to the Getting Started section as the last one
3.  rename it to "Toolkit in Action"

**Comment by eazeredo** [comment]
A future improvement is to add some context to the form, replacing the existing text with meaningful content.
