### ISSUE TITLE
Explore possibility of implementing Google Analytics + Hotjar

### ISSUE THREAD

**Issue by jaimiebutton** [thebuttonclan/pangolin#304]
- [x] make all button accounts google accounts
- [x] create a google org for button assets
- [x] invite team members to administer google org
- [x] create a new google analytics property for toolkit storybook
- [x] configure the [google analytics addon](https://storybook.js.org/addons/@storybook/addon-google-analytics) for storybook
- [x] explore hotjar

**Comment by wenzowski** [comment]
The company Google Analytics account should now be available to all team members
