### ISSUE TITLE
bcgov-theme: Input width 100% not applied

### ISSUE THREAD

**Issue by pbastia** [thebuttonclan/pangolin#350]
**Specifications**

package: @button-inc/bcgov-theme
version: 1.0.1

**Describe the bug**

The `fullWidth` directive on the `Input` component doesn't render properly (see [here](https://github.com/button-inc/service-development-toolkit/blob/6411acff6f8fe0ac5dea6fbd5ab8c7eb28377c7c/packages/bcgov-theme/src/Input.tsx#L50))
`Input` components only render with the regular  width

I highlighted the `<Grid>` container in gray:
![image](https://user-images.githubusercontent.com/11507754/144893297-bb3c7d2a-27b3-4176-99af-1bf67543629f.png)

**How to reproduce**

Render any instance of the `Input` component inside a bcgov-theme `<Grid><Grid.Row><Grid.Col>...</Grid...>` 

**Expected behavior**

The input takes 100% of the available width
![image](https://user-images.githubusercontent.com/11507754/144896342-f7ce1900-c5b1-486d-9e0c-3c4c2d61b047.png)

**Logs/tracebacks**

**Additional context**

The problem could be fixed by adding some jsx styles:
```
      <Input
        ...
      />
      <style jsx>
        {`
          :global(input) {
            width: 100%;
          }
        `}
      </style>
```

**Comment by tmastrom** [comment]
in helper.ts, the createStyleBuilder function does not apply styles because 
```
forEach(staticProps, key => {
          // if the style has not been overriden by a selected style, apply the default static style
          if (!isTrue(props, key)) styles += staticStyles[key];
        });
```

**Comment by AntBush** [comment]
Hey @pbastia we could not reproduce the behaviour in this ticket, see https://github.com/button-inc/service-development-toolkit/pull/457 for some details.
