### ISSUE TITLE
Error handling on onFormEnd and onPost

### ISSUE THREAD

**Issue by BryanGK** [thebuttonclan/pangolin#394]
**Is your feature request related to a problem? Please describe.**

There needs to be clear error handling on theses functions so that the app doesn't crash whenever and un-handled exception occurs

**Describe the solution you'd suggest**

Wrap the functions in try/catch blocks and bubble the stack trace to the top

**Comment by jjamieson1** [comment]
It appears that the error state is handled, just not handled in a graceful, user centric, usable way. 
```
 onFormEnd: (errors: [], finishedFormData: any) => {
    if (errors) console.error(errors);

 onFormEnd: (errors: [], _formData: any) => {
    console.log('completed a form');
    if (errors) console.error(errors);
```

The error is sent to the console.log, hidden from the user.  If we are improving this process, and making it more inclusive of end users I would ask the questing to the service designers on how this should be implemented from a user experience perspective.  

For example:  

1.  For Form submission failures from a backend rejection, tagged with a particular http 400 error,  display the user formatted error message above the correct form field and create a list of submission errors above the form.
2. For 50x errors(errors that cannot be recovered from)  redirect the user and attached the error message to a failed system error page  describing the users escalation steps.
3. 401 -403 message (auth state lost) , redirect user to the login page with the appropriate error message.

**Comment by jennalmcneil** [comment]
Next step: what are the common errors? What are the errors when the database is unavailable? What do we want to bubble up to the user? How do we create an abstraction that is human readable? What should those be? 
jenna to schedule a call with Zoey and James to map out possible paths. Perhaps we want a public facing support system to look at what is happening with the issue?

**Comment by AntBush** [comment]
I'd like to note, the code excerpt above is located in one of the example apps. 
 
I believe that the card is asking about the two functions found under `packages/form-schema/src/utils/validationUtils.ts` and `packages/form-schema/src/utils/cleanDataUtils.ts`

**Comment by AntBush** [comment]
We will not be proceeding with this change, as it does not meet the standard with the rest of the codebase
