### ISSUE TITLE
Description fields of non-datepicker components refer to datepicker

### ISSUE THREAD

**Issue by BCerki** [thebuttonclan/pangolin#510]
**Specifications**

n/a

**Describe the bug**

In some of the components' stories, the `args.ts` refers to `datepicker` instead of the component name (I suspect it was a copy/paste thing). 

**How to reproduce**

e.g. `packages/bcgov-theme/stories/input/args.ts`

**Expected behavior**

The args should refer to the correct component. Search for `description: 'The size of the datepicker'` to find the instances.

**Logs/tracebacks**

n/a

**Additional context**

**Comment by tmastrom** [comment]
This has been cleaned up in a different PR
